<a href="https://colab.research.google.com/github/bam396/nyu-python-public-policy/blob/master/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HOMEWORK 3 Coding: Using keywords to categorize 311 requests

# Step 1 
Create a function that checks each row in the 311 dataframe to see if the word "graffiti" is present in either the complaint_type value or descriptor value. Both columns may contain the word, so you should check both. If the word "graffiti" is found, the function should return the boolean value True. If "graffiti" is not found, the function should return the boolean value False.

1.   Hint 1: The same way that we checked if the string "BRONX" existed in the community_board value in the cb_counts table during the lecture, you can check if "graffiti" exists in the descriptor or complaint_type values.
2.   Hint 2: The descriptor column contains some null/NaN values. You'll have trouble running a function on these. Before your function checks if "graffiti" is present in descriptor, the function should make sure that a descriptor value exists using pd.notnull(row.descriptor)
3. Hint 3: Capitalization may be inconsistent. It could help to use .lower() to convert strings to lowercase.

In [1]:
import pandas as pd
from google.colab import drive
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

To help make this assignment easier, I have created a smaller subset of the 311 data for you to use. It's named cleaned_311_data_hw3.csv and it's shared with you on Google Drive. This smaller dataset only contains ~65,000 records from relevant complaint type categories. df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [0]:
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [3]:
df['complaint_type'] = df['complaint_type'].str.lower()

df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,maintenance or facility,Structure - Outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,maintenance or facility,Garbage or Litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)"
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,maintenance or facility,Hours of Operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,maintenance or facility,Garbage or Litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,maintenance or facility,Garbage or Litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
df = df[pd.notnull(df.complaint_type)]

In [5]:
df['descriptor'] = df['descriptor'].str.lower()

df.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)"
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,maintenance or facility,hours of operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
df = df[pd.notnull(df.descriptor)]

# Step 2. Apply the function created in Step 1 to the 311 dataframe and create a new column called graffiti_flag that captures the output from the function.

Tip: There are two checks you can use to confirm that the function worked as expected.
Group by graffiti_flag to make sure there are records tagged as True.
Using only the records where graffiti_flag is True (sample[sample.grafitti_flag]), group by complaint_type to make sure that more than one complaint_type is included.

In [14]:
def graffiti_complaint(row):
  if 'graffiti' in row.complaint_type:
      return 'True'
  elif 'graffiti' in row.descriptor:
      return 'True'
  else:
    return 'False' 

df['graffiti_flag'] = df.apply(graffiti_complaint, axis=1)

df.head(50)

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
0,238,238,39887282,08/01/2018 01:42:01 AM,08/14/2018 02:42:12 PM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 01:42:01 AM,The Department of Parks and Recreation has com...,08/14/2018 02:42:12 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,First Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,353,353,39889407,08/01/2018 03:20:07 AM,08/23/2018 11:15:00 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11434.0,NaN,NaN,NaN,NaN,BAISLEY BOULEVARD,MERRICK BOULEVARD,INTERSECTION,JAMAICA,NaN,NaN,Closed,08/04/2018 03:20:07 AM,The Service Request submitted did not have suf...,08/23/2018 11:15:00 AM,12 QUEENS,NaN,QUEENS,1048111.0,188479.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683778,-73.769744,"(40.68377771085733, -73.76974413109498)",False
2,403,403,39893067,08/01/2018 04:19:15 AM,08/02/2018 08:19:55 AM,DPR,Department of Parks and Recreation,maintenance or facility,hours of operation,Park,11206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 04:19:15 AM,The Department of Parks and Recreation has com...,08/02/2018 08:19:55 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Ten Eyck Plaza,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,655,655,39890578,08/01/2018 07:32:33 AM,08/16/2018 10:28:38 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11691.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAR ROCKAWAY,NaN,NaN,Closed,08/04/2018 07:32:33 AM,The Department of Parks and Recreation has com...,08/16/2018 10:28:38 AM,14 QUEENS,NaN,QUEENS,NaN,NaN,PHONE,Westbourne Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,658,658,39896325,08/01/2018 07:33:12 AM,09/04/2018 05:38:02 PM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLUSHING,NaN,NaN,Closed,08/04/2018 07:33:12 AM,The condition was inspected and it was determi...,09/04/2018 05:38:02 PM,07 QUEENS,NaN,QUEENS,NaN,NaN,MOBILE,Maple Playground,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,661,661,39895587,08/01/2018 07:34:44 AM,08/10/2018 01:45:07 PM,DPR,Department of Parks and Recreation,maintenance or facility,unsecured facility,Park,10033.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/04/2018 07:34:44 AM,The Department of Parks and Recreation has com...,08/10/2018 01:44:53 PM,12 MANHATTAN,NaN,MANHATTAN,NaN,NaN,PHONE,Fort Tryon Park - Anne Loftus Playground,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,713,713,39890857,08/01/2018 07:53:38 AM,08/08/2018 04:21:55 PM,DPR,Department of Parks and Recreation,maintenance or facility,grass/weeds,Street/Curbside,11429.0,211 STREET,211 STREET,104 AVENUE,HOLLIS AVENUE,NaN,NaN,BLOCKFACE,QUEENS VILLAGE,NaN,NaN,Closed,08/15/2018 07:53:38 AM,The Service Request submitted did not have suf...,08/08/2018 04:21:55 PM,13 QUEENS,NaN,QUEENS,1054213.0,198447.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.711091,-73.747639,"(40.711091308732435, -73.74763946439865)",False
7,789,789,39894929,08/01/2018 08:07:49 AM,08/07/2018 12:20:24 PM,DOT,Department of Transportation,broken parking meter,coin or card did not register,Street,10461.0,NaN,NaN,NaN,NaN,WESTCHESTER AVENUE,COLONIAL AVENUE,INTERSECTION,BRONX,NaN,NaN,Closed,08/21/2018 08:07:49 AM,General maintenance and cleaning is on a regul...,08/07/2018 12:20:24 PM,10 BRONX,NaN,BRONX,1031884.0,249950.0,PHONE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.852601,-73.827816,"(40.852601460220185, -73.82781602326443)",False
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True
10,964,964,39897349,08/01/2018 08:40:34 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,10467.0,345 EAST 205 STREET,EAST 205 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BRONX,2.033500e+09,BRONX,1018509.0,257554.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873534,-73.876124,"(40.87353414980636, -73.87612406980227)",True
11,1001,1001,39894633,08/01/2018 08:46:27 AM,08/23/2018 09:42:02 AM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,11201.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/15/2018 08:46:27 AM,Upon inspection the reported condition was not...,08/23/2018 09:42:02 AM,02 BROOKLYN,NaN,BROOKLYN,NaN,NaN,PHONE,Adam Yauch Park,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
12,1007,1007,39893314,08/01/2018 08:47:45 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11220.0,5506 5 AVENUE,5 AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BROOKLYN,3.008310e+09,BROOKLYN,980544.0,173249.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642204,-74.013354,"(40.64220432954161, -74.01335393443593)",True
13,1013,1013,39897422,08/01/2018 08:49:15 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,884 HART STREET,HART STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.032360e+09,BROOKLYN,1005915.0,195340.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702813,-73.921863,"(40.70281342017164, -73.92186290937498)",True
14,1050,1050,39888412,08/01/2018 08:56:53 AM,08/09/2018 08:29:37 AM,DOT,Department of Transportation,broken parking meter,coin or card did not register,Street,10458.0,NaN,NaN,NaN,NaN,EAST FORDHAM ROAD,BELMONT AVENUE,INTERSECTION,BRONX,NaN,NaN,Closed,08/21/2018 08:56:53 AM,General maintenance and cleaning is on a regul...,08/09/2018 08:29:37 AM,06 BRONX,NaN,BRONX,1016474.0,251903.0,PHONE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.858032,-73.883510,"(40.85803154781598, -73.88350951977466)",False
15,1113,1113,39890371,08/01/2018 09:05:14 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,39 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,01 BROOKLYN,3.028270e+09,BROOKLYN,1000125.0,201791.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720532,-73.942730,"(40.720532158642264, -73.94272993232262)",True
16,1125,1125,39890363,08/01/2018 09:06:03 AM,10/03/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11222.0,37 NORTH HENRY STREET,NORTH HENRY STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/23/2018 02:36:05 PM,01 BROOKLYN,3.028278e+09,BROOKLYN,1000129.0,201759.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720444,-73.942716,"(40.72044431919613, -73.94271557756703)",True
17,1196,1196,39898317,08/01/2018 09:15:07 AM,08/01/2018 11:28:16 AM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,11223.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/15/2018 09:15:07 AM,Upon inspection the reported condition was not...,08/01/2018 11:28:16 AM,13 BROOKLYN,NaN,BROOKLYN,NaN,NaN,MOBILE,Scarangella Park,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
18,1247,1247,39890214,08/01/2018 09:23:58 AM,08/07/2018 08:25:22 AM,DOT,Department of Transportation,broken parking meter,no receipt,Street,11101.0,NaN,NaN,NaN,NaN,JACKSON AVENUE,43 AVENUE,INTERSECTION,LONG ISLAND CITY,NaN,NaN,Closed,08/22/2018 09:23:58 AM,General maintenance and cleaning is on a regul...,08/07/2018 08:25:22 AM,02 QUEENS,NaN,QUEENS,1000537.0,211627.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.747529,-73.941220,"(40.74752880238678, -73.94121980592674)",False
19,1253,1253,39891954,08/01/2018 09:24:17 AM,08/07/2018 08:29:29 AM,DOT,Department of Transportation,broken parking meter,out of order,Street,10461.0,25 WESTCHESTER SQUARE,WESTCHESTER SQUARE,BENSON STREET,LANE AVENUE,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,08/21/2018 09:24:17 AM,The Department of Transportation inspected the...,08/07/2018 08:29:29 AM,10 BRONX,2.039840e+09,BRONX,1027602.0,245645.0,PHONE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.840808,-73.843322,"(40.84080758451802, -73.84332208936512)",False
20,1320,1320,39895058,08/01/2018 09:31:14 AM,11/29/2018 03:00:15 PM,DPR,Department of Parks and Recreation,maintenance or facility,grass/weeds,Park,10467.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BRONX,NaN,NaN,Closed,08/15/2018 09:31:14 AM,The Department of Parks and Recreation has com...,11/29/2018 03:00:15 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,Bronx Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
21,1361,1361,39897421,08/01/2018 09:34:51 AM,08/27/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11207.0,830 KNICKERBOCKER AVENUE,KNICKERBOCKER AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.034240e+09,BROOKLYN,1010201.0,191407.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692007,-73.906420,"(40.692006725226506, -73.90642016600616)",True
22,1379,1379,39894550,08/01/2018 09:37:09 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,663 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,"The cleaning crew was dispatched, but the owne...",10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006583.0,188415.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683804,-73.919477,"(40.68380424457166, -73.91947665760173)",True
23,1383,1383,39898718,08/01/2018 09:37:50 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,11233.0,661 MACDONOUGH STREET,MACDONOUGH STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/03/2018 01:02:01 PM,03 BROOKLYN,3.014970e+09,BROOKLYN,1006568.0,188413.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683799,-73.919531,"(40.6837987928642, -73.9195307478448)",True
24,1455,1455,39898200,08/01/2018 09:43:35 AM,08/21/2018 10:42:29 AM,DOITT,Department of Information Technology and Telec...,public payphone complaint,phone blocking sidewalk,Street and Sidewalk,10022.0,111 EAST 57 STREET,EAST 57 STREET,PARK AVENUE,LEXINGTON AVENUE,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,08/31/2018 09:43:35 AM,Both preliminary and follow-up inspections hav...,08/21/2018 10:42:29 AM,05 MANHATTAN,1.013128e+09,MANHATTAN,992529.0,216658.0,PHONE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.761349,-73.970115,"(40.761348741503, -73.9701146821389)",False
25,1507,1507,39896760,08/01/2018 09:47:21 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11222.0,239 INDIA STREET,INDIA STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Open,09/06/2018 10:04:56 AM,The graffiti on this property has been schedul...,08/07/2018 10:04:56 AM,01 BROOKLYN,3.025340e+09,BROOKLYN,998030.0,206239.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.732744,-73.950279,"(40.73274434563595, -73.95027866755898)",True
26,1521,1521,39895320,08/01/2018 09:49:12 AM,09/24/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11435.0,137-77 QUEENS BOULEVARD,QUEENS BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The City has removed the graffiti from this pr...,10/03/2018 01:02:01 PM,08 QUEENS,4.096510e+09,QUEENS,1034498.0,197615.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.708942,-73.818759,"(40.708941601133574, -73.81875856157347)",True
27,1545,1545,39893313,08/01/2018 09:51:45 AM,11/05/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11435.0,138-76 QUEENS BOULEVARD,QUEENS BOULEVARD,NaN,NaN,NaN,NaN,ADDRESS,Jamaica,NaN,NaN,Closed,10/10/2018 09:00:21 AM,The cleaning crew could not locate the propert...,12/27/2018 03:04:35 PM,08 QUEENS,4.096440e+09,QUEENS,1034971.0,196856.0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.706856,-73.817058,"(40.706855631355445, -73.81705820212048)",True
28,1558,1558,39898605,08/01/2018 09:53:24 AM,08/08/2018 07:52:46 AM,DOT,Department of Transportation,broken parking meter,no receipt,Street,10468.0,2543 JEROME AVENUE,JEROME AVENUE,EAST 190 STREET,WEST 192 STREET,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,08/22/2018 09:53:24 AM,The Department of Transportation inspected the...,08/08/2018 07:52:46 AM,07 BRONX,2.032010e+09,BRONX,1012025.0,254323.0,PHONE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.864689,-73.899583,"(40.86468883208488, -73.89958271030346)",False
29,1607,1607,39893340,08/01/2018 09:59:48 AM,08/06/2018 01:05:08 PM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 09:59:48 AM,The Department of Parks and Recreation has com...,08/06/2018 01:05:08 PM,10 BROOKLYN,NaN,BROOKLYN,NaN,NaN,PHONE,Leif Ericson Park,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
30,1718,1718,39896802,08/01/2018 10:11:55 AM,08/17/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Comercial,11210.0,848 EAST 43 STREET,EAST 43 STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,17 BROOKLYN,3.077260e+09,BROOKLYN,1002199.0,170405.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634381,-73.935331,"(40.634380746832456, -73.93533143824904)",True
31,1744,1744,39895593,08/01/2018 10:14:04 AM,08/01/2018 02:54:47 PM,DOT,Department of Transportation,highway condition,pothole - highway,Highway,11220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,NaN,The Department of Transportation has completed...,08/01/2018 02:54:47 PM,0 Unspecified,NaN,Unspecified,975738.0,173048.0,PHONE,Unspecified,Unspecified,NaN,NaN,NaN,Belt Pkwy,East/Queens Bound,Ramp,65th St - 67th St (Exit 1),40.641649,-74.030671,"(40.64164931277517, -74.03067127531824)",False
32,1777,1777,39897569,08/01/2018 10:19:15 AM,08/22/2018 11:15:56 AM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 10:19:15 AM,The Department of Parks and Recreation has com...,08/22/2018 11:15:56 AM,01 MANHATTAN,NaN,MANHATTAN,NaN,NaN,PHONE,City Hall Park,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
33,1871,1871,39897626,08/01/2018 10:29:37 AM,08/07/2018 10:25:42 AM,DOT,Department of Transportation,broken parking meter,coin or card did not register,Street,10002.0,328 GRAND STREET,GRAND STREET,ORCHARD STREET,LUDLOW STREET,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,08/21/2018 10:29:37 AM,The Department of Transportation inspected the...,08/07/2018 10:25:42 AM,03 MANHATTAN,1.004080e+09,MANHATTAN,986933.0,200533.0,PHONE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.717093,-73.990321,"(40.717093088071245, -73.99032140771455)",False
34,1892,1892,39890533,08/01/2018 10:32:39 AM,09/04/2018 11:52:50 AM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,10034.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,08/15/2018 10:32:39 AM,The Department of Parks and Recreation has com...,09/04/2018 11:52:50 AM,12 MANHATTAN,NaN,MANHATTAN,NaN,NaN,ONLINE,Inwood Hill Park - Indian Road Playground,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
35,1921,1921,39890768,08/01/2018 10:35:38 AM,08/06/2018 01:04:06 PM,DPR,Department of Parks and Recreation,maintenance or facility,grass/weeds,Park,11220.0,NaN,NaN,NaN,NaN,COLONIAL ROAD,SHORE ROAD,INTERSECTION,BROOKLYN,NaN,NaN,Closed,08/15/2018 10:35:38 AM,The Department of Parks and Recreation has com...,08/06/2018 01:04:06 PM,10 BROOKLYN,NaN,BROOKLYN,976157.0,172729.0,PHONE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.640774,-74.029161,"(40.64077411899319, -74.02916111078318)",False
36,1951,1951,39893642,08/01/2018 10:37:21 AM,08/15/2018 01:45:28 PM,DPR,Department of Parks and Recreation,maintenance or facility,grass/weeds,Street/Curbside,NaN,HYLAN BOULEVARD,HYLAN BOULEVARD,SAND LANE,WEST FINGERBOARD ROAD,NaN,NaN,NaN,NaN,NaN,NaN,Closed,08/15/2018 10:37:21 AM,The Department of Parks and Recreation has com...,08/15/2018 01:45:28 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,PHONE,Unspecified,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
37,2006,2006,39899215,08/01/2018 10:42:16 AM,08/01/2018 11:16:34 AM,NYPD,New York City Police Department,graffiti,police report not requested,Street/Sidewalk,11417.0,138-30 LAFAYETTE STREET,LAFAYETTE STREET,ALBERT ROAD,149 AVENUE,NaN,NaN,ADDRESS,OZONE PARK,NaN,Precinct,Closed,08/01/2018 06:42:16 PM,The Police Department responded to the complai...,08/01/2018 11:16:34 AM,10 QUEENS,4.114030e+09,QUEENS,1027208.0,183865.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.671239,-73.845141,"(40.67123947322719, -73.84514076011867)",True
38,2103,2103,39892182,08/01/2018 10:55:12 AM,08/21/2018 05:24:56 PM,DPR,Department of Parks and Recreation,maintenance or facility,structure - outdoors,Park,11375.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FOREST HILLS,NaN,NaN,Closed,08/15/2018 10:55:12 AM,The condition was inspected and it was determi...,08/21/2018 05:24:56 PM,0 Unspecified,NaN,Unspecified,NaN,NaN,ONLINE,Flushing Meadows Corona Park,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
39,2116,2116,39897903,08/01/2018 10:56:19 AM,08/02/2018 08:16:52 AM,DPR,Department of Parks and Recreation,maintenance or facility,garbage or litter,Park,11211.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BROOKLYN,NaN,NaN,Closed,08/04/2018 10:56:19 AM,The Department of Parks and Recreation has com...,08/02/2018 08:16:52 AM,01 BROOKLYN,NaN,BROOKLYN,NaN,NaN,PHONE,Roebling Playground,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [15]:
# checking to see if the function worked
df_flag = df.groupby('graffiti_flag').size().reset_index(name='graffiti_flag_group').sort_values('graffiti_flag', ascending=False)

df_flag.head()

  graffiti_flag  graffiti_flag_group
1          True                26371
0         False                38206

# Step #3
Create another dataframe df_graffiti that only contains records where graffiti_flag is True. df_graffiti = df[df.grafitti_flag]

In [0]:
df_graffiti = df[df.graffiti_flag=="True"]

In [0]:
df_graffiti

In [32]:
df_graffiti.head()

,Unnamed: 0,Unnamed: 0.1,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,graffiti_flag
8,860,860,39897352,08/01/2018 08:21:08 AM,NaN,DSNY,Department of Sanitation,graffiti,graffiti,NaN,NaN,141 141 ST,141 ST,NaN,NaN,NaN,NaN,ADDRESS,NaN,NaN,NaN,Open,NaN,NaN,08/01/2018 08:21:08 AM,Unspecified QUEENS,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9,876,876,39891938,08/01/2018 08:24:41 AM,08/30/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,237 IRVING AVENUE,IRVING AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/20/2018 03:18:01 PM,04 BROOKLYN,3.032900e+09,BROOKLYN,1007216.0,194542.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700620,-73.917173,"(40.70061981717157, -73.91717344071574)",True
10,964,964,39897349,08/01/2018 08:40:34 AM,08/23/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Residential,10467.0,345 EAST 205 STREET,EAST 205 STREET,NaN,NaN,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BRONX,2.033500e+09,BRONX,1018509.0,257554.0,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873534,-73.876124,"(40.87353414980636, -73.87612406980227)",True
12,1007,1007,39893314,08/01/2018 08:47:45 AM,08/20/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11220.0,5506 5 AVENUE,5 AVENUE,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,07 BROOKLYN,3.008310e+09,BROOKLYN,980544.0,173249.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642204,-74.013354,"(40.64220432954161, -74.01335393443593)",True
13,1013,1013,39897422,08/01/2018 08:49:15 AM,08/28/2018 12:00:00 AM,DSNY,Department of Sanitation,graffiti,graffiti,Mixed Use,11237.0,884 HART STREET,HART STREET,NaN,NaN,NaN,NaN,ADDRESS,BROOKLYN,NaN,NaN,Closed,09/06/2018 10:04:56 AM,The City has removed the graffiti from this pr...,09/13/2018 04:19:12 PM,04 BROOKLYN,3.032360e+09,BROOKLYN,1005915.0,195340.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702813,-73.921863,"(40.70281342017164, -73.92186290937498)",True

# Step #4
Group your dataframe df_graffiti to get the count of requests per community_board. Use .nlargest() to identify which Community District has the highest count.

In [31]:
df_graffiti.groupby('community_board').size().nlargest()

community_board
01 BROOKLYN     1797
03 MANHATTAN    1593
04 BROOKLYN     1429
03 BROOKLYN     1252
05 BROOKLYN      962
dtype: int64